image: ruby:2.5

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  GEM_PATH: .bundle
  BUNDLER_PATH: .bundle/bin

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .bundle
    - .npm

before_script:
  - apt-get update -y
  - apt-get install -y build-essential bash git rsync curl gnupg2
  - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
  - curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null
  - gpg --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  - echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list
  - apt-get update -y
  - apt-get install -y nodejs yarn
  - \curl -sSL https://get.rvm.io | bash -s stable
  - source /root/.bashrc
  - chmod +x setup.sh && bash setup.sh

test:
  stage: test
  script:
  - $BUNDLER_PATH/bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - $BUNDLER_PATH/bundle exec jekyll build -d public
  - find public -type f -regex '.*\.\(html\)$' -exec npm run minify-html {} \;
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
    - public
  only:
  - master
